FROM ubuntu:24.04
ENV DOCKER_BUILD=true
ENV DEBIAN_FRONTEND=noninteractive

# install.sh が内部で使うツールを入れる
RUN apt-get update && apt-get install -y \
    git curl build-essential sudo \
    && apt-get clean

# 今いる場所（dotfiles直下）のファイルをすべてコンテナの /root/.dotfilesに送る
WORKDIR /root/.dotfiles
COPY . .

# コピーされたinstall.shを実行
RUN chmod +x install.sh && ./install.sh

# Neovimをヘッドレス（画面なし）で起動し、プラグインをインストールして終了
RUN /root/.local/bin/mise exec -- nvim --headless "+Lazy! sync" +qa

# docker run時にデフォルトで実行されるコマンド
CMD ["fish"]

