FROM dev-base

# Haskellツールチェーン（GHCupなど）のインストール
# 非対話モードでHLS（Language Server）まで入れる
ENV BOOTSTRAP_HASKELL_NONINTERACTIVE=1
ENV BOOTSTRAP_HASKELL_INSTALL_HLS=1
ENV BOOTSTRAP_HASKELL_INSTALL_STACK=1
# latestだとHLSが存在しないため、安定版をインストール
ENV BOOTSTRAP_HASKELL_GHC_VERSION=9.12.2 
ENV BOOTSTRAP_HASKELL_ADJUST_CABAL_CONFIG=1
# GHCupのインストール先
ENV PATH="/root/.ghcup/bin:${PATH}"

# GHCupのインストール
RUN curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

RUN ghcup set ghc 9.12.2 && ghcup set hls latest

# 作業ディレクトリの設定
WORKDIR /workspace
CMD ["/home/linuxbrew/.linuxbrew/bin/fish"]
